### ISSUE TITLE
Christ Church msDescs need proper shelfmark

### ISSUE THREAD

**Issue by jamescummings** [holfordm/tolkien-xml#12]
@holfordm 

I think I mentioned before that the Christ Church msDescs need a proper shelfmark in their 
msIdentifier/idno  (which might be more consistent)  This needs to start with an alphabetic character so something like MS Christ Church 100 rather than just 100 would be a possible suggestion.

**Comment by holfordm** [comment]
changed to Christ Church MS {no}
