### ISSUE TITLE
correct usage of altIdentifier in msPart

### ISSUE THREAD

**Issue by holfordm** [holfordm/tolkien-xml#3]
`<msPart>/<altIdentifier type="partial">` needs to be corrected to `<msPart>/<msIdentifier>` or `<msPart>/<msIdentifier>/<altIdentifier type="partial">`. (Did the usage of `<altIdentifier>` change at some point?

**Comment by jamescummings** [comment]
@holfordm Just to note that current my conversion is just turning this into msIdentifier since all of these altIdentifiers seem to have an idno in them.  And yes, using altIdentifier  directly inside msPart instead of inside an msIdentifier has be deprecated for awhile.

**Comment by jamescummings** [comment]
In regenerating the converted files and revalidating I've noticed that where there is an idno and a note in there then this is a problem since msIdentifier can't have note in it.  So I'm now doing it so that for every msPart/altIdentifier I create msPart/msIdentifier/altIdentifier

**Comment by jamescummings** [comment]
I believe this is done, so I'm closing it. re-open if it is still a problem.
