### ISSUE TITLE
convert filenames and correct xml:ids

### ISSUE THREAD

**Issue by holfordm** [holfordm/tolkien-xml#7]
Convert filenames to a string based on the MS. title. Parentheses `( )` can be removed (but NB, do NOT remove the CONTENT of the parentheses). Periods` .` can be removed. Whitespace can be replaced with `_`. `/` replace with `--`. `*` replace with `star`
Use the filename to create the xml:id for `<msDesc>`
Create xml:id for each `<msPart>` and `<msItem>` based on the above xml:id (e.g `....._part_1_item_1`?)

**Comment by jamescummings** [comment]
I believe this is done, so I'm closing it. re-open if it is still a problem.
