### ISSUE TITLE
convert origin>date to origDate

### ISSUE THREAD

**Issue by holfordm** [holfordm/tolkien-xml#8]
convert `<date>` inside `<origin>` to `<origDate>`, retain existing attributes. 
Note there may be more than one `<date>` inside `<origin>`

**Comment by jamescummings** [comment]
@holfordm Just to check. Currently I have all dates inside origin made into origDate but I could have this be the *first* one only if that was more accurate?  I remember you answered this question for me, but I just can't find it now.

**Comment by holfordm** [comment]
no, all _date_ to _origDate_ inside _origin_ is correct!


________________________________

**Comment by jamescummings** [comment]
I believe this is done, so I'm closing it. re-open if it is still a problem.
