### ISSUE TITLE
Assign language to each msItem

### ISSUE THREAD

**Issue by holfordm** [holfordm/tolkien-xml#9]
Where language is only specified at the top level of the description (`<msContents>/<textLang>`), the language should be copied into each `<msItem>`. This is to make the SOLR indexing easier.
Note that this will only be possible when there is a single language in the manuscript (`textLang[parent::msContents and not(@otherLangs)]`)

**Comment by jamescummings** [comment]
I believe this is done, so I'm closing it. re-open if it is still a problem.
